server:
  port: 8761

eureka:
  instance:
    hostname: ccd-discovery.dcos.os
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://ccd-discovery.dcos.os:${server.port}/eureka/

spring.cloud.config.discovery.enabled: true