server:
  port: 8761

eureka:
  instance:
    hostname: 10.10.100.50
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://10.10.100.50:${server.port}/eureka/

spring.cloud.config.discovery.enabled: true