server:
  port: 9007

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
  
ldap:
  contextSource:
    url: jdc.joyoudata.com:389
    userDn: uid=shaopeng.yuan@joyoudata.com,ou=北京办,ou=深圳市卓优数据科技有限公司
    password: a12345678A
    username: shaopeng.yuan
    base: dc=joyoudata,dc=com
    directory.type: NORMAL

