server:
  port: 9007

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

security:
  basic:
    enabled: false

#Client
app:
  client:
    id: sso-auth-client
    secret: mySecret
    
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 11111
      database: auth-user-server

ldap:
  contextSource:
    url: jdc.joyoudata.com:389
    userDn: uid=shaopeng.yuan@joyoudata.com,ou=北京办,ou=深圳市卓优数据科技有限公司
    password: a12345678A
    username: shaopeng.yuan
    email: shaopeng.yuan@joyoudata.com
    base: dc=joyoudata,dc=com
    directory.type: NORMAL
    searchScope: onelevel

