server:
  port: 9093
  
logging:
  level:
    root: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

security:
  basic:
    enabled: false
    
spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: mysql
    url: jdbc:mysql://192.168.119.134:3306/ccd??useUnicode=true&characterEncoding=UTF-8
    username: myusername
    password: mypassword
    driverClassName: com.mysql.jdbc.Driver    
     
ldap:
  contextSource:
    url: ldap://jdc.joyoudata.com:389
    base: DC=joyoudata,DC=com
    userDn: shaopeng.yuan@joyoudata.com
    password: a12345678A
    email: shaopeng.yuan@joyoudata.com
    
oauth2_server: 
  clients:
  - clientId: restapi
    resourceIds: rest_api,joyouResource
    clientSecret: restapipassword
    refreshTokenValidity: 4500
    accessTokenValidity: 4500
    authorities: trust,read,write
    authorizedGrantTypes: client_credentials,authorization_code,implicit,password,refresh_token
    scope: trust,read,write
    scoped: true
    secretRequired: true
    autoapprove: true
  - clientId: project_restapi
    resourceIds: rest_api,joyouResource
    clientSecret: projectpassword
    refreshTokenValidity: 4500
    accessTokenValidity: 4500
    authorities: trust,read,write
    authorizedGrantTypes: client_credentials,authorization_code,implicit,password,refresh_token
    scope: trust,read,write
    scoped: true
    secretRequired: true
    autoapprove: true
  users: 
  - username: admin
    password: 123.com
    email: admin@joyoudata.com
    scope: read,write,trust