server:
  port: 9093
  
logging:
  level:
    root: info

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-server-connect-timeout-seconds: 30
    serviceUrl:
      defaultZone: http://ccd-discovery.dcos.os:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    hostname: ccd-uaa.dcos.os

security:
  basic:
    enabled: false
    
spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: mysql
    url: jdbc:mysql://192.168.119.139:3306/mydb?useUnicode=true&characterEncoding=UTF-8
    username: myusername
    password: mypassword
    driverClassName: com.mysql.jdbc.Driver    
     
ldap:
  contextSource:
    url: ldap://test:27636
    base: DC=joyoudata,DC=com
    userDn: test
    password: test
    email: test
    
oauth2_server: 
  clients:
  - clientId: restapi
    resourceIds: rest_api,joyouResource
    clientSecret: restapipassword
    refreshTokenValidity: 4500
    accessTokenValidity: 4500
    authorities: read,write,trust
    authorizedGrantTypes: client_credentials,authorization_code,implicit,password,refresh_token
    scope: openid
    scoped: true
    secretRequired: true
    autoapprove: true
  - clientId: project_restapi
    resourceIds: rest_api,joyouResource
    clientSecret: projectpassword
    refreshTokenValidity: 4500
    accessTokenValidity: 4500
    authorities: read,write,trust
    authorizedGrantTypes: client_credentials,authorization_code,implicit,password,refresh_token
    scope: trust,read,write
    scoped: true
    secretRequired: true
    autoapprove: true
  users: 
  - username: admin
    password: test
    email: admin@joyoudata.com
    role: ROLE_USER,ROLE_ADMIN
