server:
  port: 9097
  
logging:
  level:
    root: info

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-server-connect-timeout-seconds: 30
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true

zuul:
  routes:
    apigatewayservice: 
      path: /zuulgateway/**
      service-id: apigatewayservice
    project-service: 
      path: /project-service/**
      service-id: project-service
      
ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
  eureka:
    enabled: true

security:
  sessions: ALWAYS
  oauth2:
    client:
      access-token-uri: http://127.0.0.1:9093/oauth/token
      user-authorization-uri: http://127.0.0.1:9093/oauth/authorize
      client-id: restapi
      client-secret: restapipassword
    resource:
      token-info-uri: http://127.0.0.1:9093/oauth/check_token