server:
  port: 9097
  
logging:
  level:
    root: info

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-server-connect-timeout-seconds: 30
    serviceUrl:
      defaultZone: http://ccd-discovery.dcos.os:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    hostname: ccd-apigateway.dcos.os

zuul:
  routes:
    apigatewayservice: 
      sensitive-headers: 
      service-id: apigatewayservice
    project-service: 
      sensitive-headers: 
      service-id: project-service
    uaa:
      sensitive-headers: 
      service-id: uaa-service
    ui:
      sensitive-headers: 
      service-id: ui
      
spring:
  aop:
    proxy-target-class: true

security:
  oauth2:
    client:
      access-token-uri: http://ccd-uaa.dcos.os:9093/oauth/token
      user-authorization-uri: http://ccd-uaa.dcos.os:9093/oauth/authorize
      client-id: restapi
      client-secret: restapipassword
    resource:
      user-info-uri: http://ccd-uaa.dcos.os:9093/userinfo
      #token-info-uri: http://127.0.0.1:9093/oauth/check_token